apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-realtime
  labels:
    app: chat-realtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-realtime
  template:
    metadata:
      labels:
        app: chat-realtime
    spec:
      containers:
      - name: chat-realtime
        image: 21520623/chat-realtime:latest
        ports:
        - containerPort: 15001
---
apiVersion: v1
kind: Service
metadata:
  name: chat-realtime-svc
  labels:
    app: chat-realtime
spec:
  selector:
    app: chat-realtime
  ports:
    - protocol: TCP
      port: 80
      targetPort: 15001
      nodePort: 32408
  type: NodePort