apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-mongo
  template:
    metadata:
      labels:
        app: comment-mongo
    spec:
      containers:
      - name: comment-mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: comment-service
        resources:
          requests:
            memory: "125Mi"
            cpu: "0.2"
          limits:
            memory: "250Mi"
            cpu: "0.2"
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 600Mi
---
apiVersion: v1
kind: Service
metadata:
  name: comment-mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
