---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: react-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: react-frontend
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: video-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-service
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: comment-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: comment-service
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: comment-mongo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: comment-mongo-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 90
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-mongo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-mongo-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 90
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: video-mongo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-mongo-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 90