apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-master
  namespace: default
spec:
  serviceName: "redis-master"
  replicas: 3
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
      - name: redis
        image: redis:6.0
        command: ["redis-server", "/redis-master/redis.conf"]
        volumeMounts:
        - name: redis-config
          mountPath: /redis-master
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi