apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: default
data:
  redis.conf: |
    protected-mode no
    port 6379
    bind 0.0.0.0
    dir /data
    appendonly yes
    requirepass 123456