apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: redis
  labels:
    app: redis
    role: slave
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6380
  clusterIP: None
  selector:
    app: redis
    role: slave